### ISSUE TITLE
Unable to use the Native Support

### ISSUE THREAD

**Issue by Anjan62** [jopohl/urh#1040]
Hey there,
I am currently working on a project on the Linux system machine and for which I downloaded URH directly by downloading the git file and extracting the folder and further simply running the file using these commands - 
cd src
cd urh
python main.py
it run and urh opened, but now which I am clicking on options and then on devices, all the devices are marked as not available. As shown below - 

![Screenshot_2023-03-22_11_31_38](https://user-images.githubusercontent.com/65858265/226891863-b4ef00b3-5557-4654-bbd0-af7d82407437.png)

So as it says I downloaded GNU Radio by simply writing the command sudo apt-get install GNURadio. and then restart everything but still problem didn't resolved.

Then I saw the epic to forcibly enabled any module, we can do that by python setup.py --with-hackrf. I did that as well and this happened.

![Screenshot_2023-03-22_11_39_12](https://user-images.githubusercontent.com/65858265/226893139-0df11428-400b-4493-8cc7-c95ffbea2278.png)

If you can help me in any manner? I don't know what's wrong because.

Thanks
Anjan

**Comment by andynoack** [comment]
This is rather an issue for our Slack channel, because it is basically installation support. Take care that all the libs for your SDR devices are installed _before_ you rebuild the cython extensions of URH. You can do this either by clicking the according button under devices in options or run the build.py that is located at urh/src/urh/cythonext/build.py
After that native device support should be available if URH is able to build the extension for your enabled SDR.
