### ISSUE TITLE
Version with dynamic labels and variable message length

### ISSUE THREAD

**Issue by Pascal66** [jopohl/urh#1041]

**Comment by andynoack** [comment]
We have discussed this earlier and came to the conclusion that the number of use cases does not justify such a large implementation effort as well as usability issues for standard cases due to additional configuration settings like additional form fields/submenus/whatever.  This is up to a future release whenever there is enough time to do it. You are welcome to submit a pull request which we are happy to accept if the usability is not lowered for standard cases.
