### ISSUE TITLE
HackRF Gain sliders & LNA button

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#136]
Hi there,
Not really an issue but was wondering if its possible to include gain sliders and an lna button for the hackrf?
Cheers

**Comment by jopohl** [comment]
Hey @vsboost ,
thanks for bringing this up. Just some questions for clarification:
1. Are we talking about three different sliders for the HackRF?:
  - RF Gain
  - IF Gain
  - BB Gain
2. Do you know wheter the HackRF has some LNA functionality builtin? Otherwise would implement it myself. I like the idea!

**Comment by vsboost** [comment]
Sorry should have called it an "RF Amp" so the three settings would be

Slider for IF LNA gain 0-40db in 8db steps
Slider for Baseband VGA gain 0-62db in 2db steps
Button for RF amp 0db = OFF ,14db = ON

Hope that makes sense

Cheers

**Comment by jopohl** [comment]
Thanks for clarifying this @vsboost . I think it makes sense to have more control over these HackRF parameters, so I will implement this soon.

**Comment by vsboost** [comment]
Thanks Johannes
