### ISSUE TITLE
Add native support for AirSpy

### ISSUE THREAD

**Issue by bvernoux** [jopohl/urh#227]
The Gnuradio backend support already AirSpy and it works like a charm (tested on Xubuntu 16.x) but it will be even better with native support
For information native support for AirSpy API is very close to HackRF API

Contact me for free hardware (AirSpy R2 / AirSpy Mini) if you need them

**Comment by andynoack** [comment]
Hey @bvernoux
indeed we do not have AirSpys in our lab but like to have some :) If you could provide us with some hardware we were able to develop a native backend! Two samples (each kind?) would be great so that both of us can develop and test. You can contact me by Email (included in my GitHub profile) for further information.

**Comment by bvernoux** [comment]
I have contacted Johannes by Email about that

**Comment by andynoack** [comment]
Never mind
