### ISSUE TITLE
Auto assign labels

### ISSUE THREAD

**Issue by ikarus23** [jopohl/urh#382]
Hi! Is there a way to assign labels automatically? Did I miss it? I see the "Assign labels" checkbox in the in the dropdown menu next to the "Analyze" button...

Lets say I have a demodulated stream like this:
```
0001111010111111101010000 | 0101010101010101 | 000000000000 | 01001011011100010100010111011000100010 | 00000 | 11111111111 | 0000000 | 00011001000010100000
                                   1                                                2                               3                          4
```
I know "1" is the preamble, "2" is the address, "3" the payload and "4" the crc. The rest is irrelevant trash (with fixed length). Is there a way to auto assign the label "preamble" to the bit sequence of 1 and then specify the other labels with a relative offset? Removing the "trash" should be easy once everything is labelled, because I can use the "Show only labels in protocol" feature of URH.

**Comment by jopohl** [comment]
Short answer: This is not yet supported. It is coming 2018.
Long answer: Currently, the auto assign feature tries to automatically assign labels based on heuristics. We are working on improving this mechanism behind the scenes. Ideally, it won't be even necessary to specify labels manually because URH finds them itself.

For your current task you may find the ZeroHide Plugin useful, to hide all the zero trash and assign labels afterwards. This assumes, of course, that the trash always consists of zeros.

**Comment by ikarus23** [comment]
Thanks for the feedback and thanks again for this great tool. Looking forward to this feature ;)

**Comment by ikarus23** [comment]
Thank you. This project has come a far way! If I could star it again, I would! ;)
