### ISSUE TITLE
Wrong hiding when using multiple message types and labels

### ISSUE THREAD

**Issue by Nesos-ita** [jopohl/urh#451]
## Expected Behavior  
I have two message types, one label in the first, and two labels in the second.  
Hiding the label in the first message type should hide only the labelled bits, and only of that message type.  

## Actual Behavior  
If a label say "bit 1-31" bits 1-31 are hidden regardless of the message type  
Other problem: if i hide some labels, enable and disable "mark diff in protocol" in the moment i disable it, every label become visible also if it is unchecked  
checking and unchecking the label hides again the label  

## Steps to Reproduce the Problem

 1. Add two message types and one label per message type  
 2. set two rows as two different message types  
 3. hide one label  
 4. (part of) the other is hidden too  

Check the photo:  
bits 20-28 of row 2,3,4 are part of a short pause but i setted it as sync too  
![bug](https://user-images.githubusercontent.com/20688006/40673754-fd8a748e-6372-11e8-82bb-16e997608038.png)

## Platform Specifications

  - Python Version: installed 3.6 but it uses 3.5 included with the msi
  - Operating System: win8.1 x64
  - Version of URH: 2.0.4 MSI installer x64
  - URH was installed: via msi

**Comment by Nesos-ita** [comment]
mmm so how do i solve my problem? i'd like to see only "message" and not preamble/sync, possibly without editing all the signals to keep only the data part.  
also what is the point of having multiple message types if i can't keep enabled only one? for example if i have a transerceiver and i set two message types "query" and "answer" and i'm interested only in answers  
i'm a bit confused

**Comment by jopohl** [comment]
Well, in your case it would be much easier to use a Filter located at the top of Analysis as shown below:
![bildschirmfoto_2018-05-29_20-18-20](https://user-images.githubusercontent.com/18219846/40677285-8519b93c-637d-11e8-9b71-8501e020992e.png)

You would simply enter, e.g., the synchronization bits, hit "Filter" and all messages not containing this pattern will be hidden, which are the preambles in your case. Note, you must first select the "Filter" as the button uses "Search" as default.

The problem with the bit hiding is not that easy to solve. If you simply leave bits out e.g. by replacing them with a "-" you loose the ability of alignment. However, I see your point, it may confuse users as it is not the expected behaviour.

**Comment by Nesos-ita** [comment]
Nice, it works :)  i'm still a bit confused for the hiding, i have to think more about it.  
the only left problem is that hidden labels are not kept hidden:  
 - if i click mark diff (enable and disable), on disable hidden labels are shown again  
 - if i click filter (maybe this one is wanted since i'm searching/filtering for this)

**Comment by Nesos-ita** [comment]
seems that it happens if:  
 - you have two message types  
 - i setted one label per message type  
 - one label is a column other is a row and they *must* collide/intersecate  
 - hidden a label  
 - enabled and disabled show diff  

same happens if i enable and disable the first signal (but not the second)

**Comment by jopohl** [comment]
Thanks I was able to reproduce this behaviour and fixed it in #452.
