### ISSUE TITLE
High CPU using Spectrum Analyzer

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#492]
## Actual Behavior
100% CPU usage when using spectrum analyzer

## Platform Specifications

  - Operating System: Windows 10
  - Version of URH: 2.2.1
  - URH via .msi

Just realized this when my surface pro shut down, i know from experience if programs consume 100% cpu for a period of time will cause the surface pro the shut down.

![image](https://user-images.githubusercontent.com/11001973/42410844-2a431082-8234-11e8-9eae-94545a229dd3.png)

**Comment by andynoack** [comment]
I can confirm a quite high cpu and increasing RAM usage (it is for storing the waterfall information...hitting 'refresh' in the spectrum analyzer causes URH to overwrite the already taken RAM so that no additional RAM is consumed for a while again). 

However, as both illustrations are computed and rendered in real time, the resource usage doesn't  really surprise me. We exclusively use the CPU for all computations. Using GPU may be a way to go but we do not like to add another (hard) dependency and maybe exclude parts of our users (without nice graphics cards) from using URH. 
Do you have any idea or suggestion?

**Comment by vsboost** [comment]
I think it might be ok to leave this alone for the moment, i realized that if i run the surface pro on battery it only uses ~%50 CPU which i can live with - just have to remember to leave it unplugged if running the SA for a long time.

Below is the SA running on battery and then plugged in to AC power and then removed from power.

![image](https://user-images.githubusercontent.com/11001973/42415540-1aca8386-8295-11e8-8a0b-046b187bc067.png)
