### ISSUE TITLE
Bit slicing/decoding fails

### ISSUE THREAD

**Issue by mrx23dot** [jopohl/urh#979]
##### Expected Behavior
Bit slicing/thresholding fails to discriminate to 0/1

##### Screenshots
![2022-05-05 12_36_52-Window](https://user-images.githubusercontent.com/4163396/166915522-c9dce7e7-33e6-47f5-9628-8470b19fd307.jpg)

The width of high pulse is 237sample, so I set sample/symbols to same.
**I would expect decoded bits: .. 0 0 1 0 ...
But as you can see it gives       .. 1 1 1 1 ..**

Error tolerance of 1 gives same result.
Encoding is pulse-width modulation

##### Platform Specifications

 - OS: [e.g. Arch Linux] win10 x64
 - URH version: [e.g. 2.4.2]   2.9.3 x64
 - Python version: [e.g. 3.7] Python 3.7.0
 - Installed via [e.g. pip]  no, via exe

**Comment by andynoack** [comment]
URH uses a best effort method to detect the current bits. Sometimes this fails for some signals, especially when some values are extra-ordinary high or low (error tolerance 50 in this case, as you already wrote). I recommend to fix the decoding errors by either using a recording that is more clean than this one or by applying special decodings in the analysis tab. I will close here because I do not think this is a generic problem of URH here. You can use our slack channel for further discussions on particular signals.
